services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./opentele-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317" # grpc
      - "4318:4318" # http
    restart: unless-stopped
