receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/rust: # exportin to rust pipeline via oltp/http (json)
    endpoint: http://host.docker.internal:8080
    encoding: json
    compression: none

  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/rust, debug]
